a=0
b=0
c=0
def counter(x,a,b,c):
    
    if(x=='a'):
        a+=1
    elif(x=='b'):
        b+=1
    elif(x=='c'):
        c+=1
    else:
        counter(input("enter correct option"),a,b,c)
    return a,b,c


print("I’m going to ask you some questions to help you determine your current Doshic balance. "+ "Remember, you are not entirely one Dosha but rather a combination of all three in varying"+" amounts. This quiz helps you determine your primary, secondary, and tertiary Doshas. "+"Try to answer these questions honestly, rather than how you wish you were. If you have a difficult "+"time answering these questions, ask a friend or loved one who knows you well to help you. They"+" might be able to answer more objectively for you. The goal, however, is to know thyself.\n")
input("Press Enter to continue \n")  
print("1. Which most accurately describes your body?")
print("a. Naturally thin, lanky, slender")
print("b. Medium built, good muscular build")
x= input("c. Curvy, bigger built \n")  
a,b,c=counter(x,a,b,c)
print("2. How easily do you gain weight?")
print("a. Next to impossible; have to remember to eat to try not to lose any more weight")
print("b. Moderately; can lose or gain weight if I really try and can put on muscle easily")
x= input("c. Too easily; put on weight just by looking at food and have a hard time losing it \n")  
a,b,c=counter(x,a,b,c)
print("3. What are your eyes like?")
print("a. On the smaller side and actively moving")
print("b. Have a penetrating, deep gaze")
x= input("c. Big and beautiful \n")  
a,b,c=counter(x,a,b,c)
print("4. What is your skin like?")
print("a. Tends to get dry, quite thin, has visible veins")
print("b. Oily, acne-prone, has a reddish tint")
x= input("c. Moist, smooth, thick, combination \n")  
a,b,c=counter(x,a,b,c)
print("5. What is your hair like?")
print("a. Dry, frizzy, prone to split ends and breakage")
print("b. Fine, oily, tendency toward thinning or graying")
x= input("c. Thick, abundant, more on the oily side \n")  
a,b,c=counter(x,a,b,c)
print("6. What are your joints like?")
print("a. Prominent, tend to crack, often aching, injury-prone")
print("b. Flexible, agile")
x= input("c. Large, well padded \n")  
a,b,c=counter(x,a,b,c)
print("7. What is your digestion like?")
print("a. Variable—sometimes good, sometimes bad")
print("b. Strong and powerful")
x= input("c. Slow and weak \n")  
a,b,c=counter(x,a,b,c)
print("8. What is your elimination like?")
print("a. Tends toward constipation")
print("b. Regular, tends toward loose stools")
x= input("c. Thick, long, sluggish \n")  
a,b,c=counter(x,a,b,c)
print("9. Which digestive imbalances do you feel most?")
print("a. Bloating and gas")
print("b. Heartburn and acidic stomach")
x= input("c. Heaviness after eating and water retention \n")  
a,b,c=counter(x,a,b,c)
print("10. How is your body temperature?")
print("a. Always cold; prefer hot weather")
print("b. Usually warm; prefer cool weather")
x= input("c. Pretty adaptable; don’t like cold, wet weather though \n")  
a,b,c=counter(x,a,b,c)
print("11. What is your temperament like?")
print("a. Enthusiastic, vivacious, creative")
print("b. Driven, passionate, ambitious")
x= input("c. Easy-going, giving, patient \n")  
a,b,c=counter(x,a,b,c)
print("12. What are your negative traits?")
print("a. Anxious, fearful, and\or nervous")
print("b. Competitive, aggressive, and\or impatient")
x= input("c. Lonely, depressed, and\or jealous \n")  
a,b,c=counter(x,a,b,c)
print("13. How do you sleep?")
print("a. Difficulty falling asleep, wake up often")
print("b. Moderate and sound")
x= input("c. Deep and long \n")  
a,b,c=counter(x,a,b,c)
print("14. How is your memory?")
print("a. Quick to remember, quick to forget")
print("b. Medium but accurate with facts")
x= input("c. Hard time remembering but then sustained \n")  
a,b,c=counter(x,a,b,c)
print("15. How are you with money and material possessions?")
print("a. Impulsive shopper; buy things and forget about them")
print("b. Calculated shopper; spend on luxuries that are worth it")
x= input("c. Hoarder; have a hard time letting things go \n")  
a,b,c=counter(x,a,b,c)
print("16. What subjects are you most drawn toward?")
print("a. The arts, spirituality, philosophy, literature, big-picture stuff")
print("b. Business, science, law, engineering, calculated stuff")
x= input("c. Counseling, teaching, human resources, care-giving, hands-on stuff \n") 
a,b,c=counter(x,a,b,c)
if(a>b and a>c):
    print(" VATA")
    print(" Vata mind: Creative \n Vata body: Lean \n Vata obstacle: Sticking to one idea \n Vata imbalance: Anxiety, digestive trouble")
elif(b>a and b>c):
    print("PITTA")
    print("Pitta mind: Ambitious \n pitta body: Athletic \n Pitta obstacle: Burnout \n Pitta imbalance: Anger, heartburn")
elif(c>b and a<c):
    print("KAPHA")
    print("Kapha mind: Peaceful \n Kapha body: Rounded \n Kapha obstacle: Putting others before self \n Kapha imbalance: Depression, weight gain")